# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab876d1b8f78e0468676040f6b4eff40a709e42e5ce77dc58ef32ebfa7c231686e82ad3299c58fbb91c8093164ac4689b4601e88a786593e14c48afb995f93c

test:
  secret_key_base: a97ab07912eed51d045b607ac884d554f90369c8fc5af7ec99fa8d3211eaec4d45c594ccce3e05ca8ae4daf8aa660f8ee1e664b3cfa713d5600be8d24e233233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
